# Generated by Django 2.2.4 on 2019-08-13 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default=None, null=True)),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='img/aboutme/')),
                ('registed', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, default=None, null=True)),
                ('month', models.IntegerField(blank=True, default=None, null=True)),
                ('text', models.TextField(blank=True, default=None, null=True)),
                ('registed', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('repository', models.URLField(blank=True, default=None, null=True)),
                ('started', models.CharField(blank=True, default=None, max_length=7, null=True)),
                ('finished', models.CharField(blank=True, default=None, max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('point', models.IntegerField(blank=True, default=None, null=True)),
                ('icon', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
