# Generated by Django 2.2.4 on 2019-08-14 02:33

from django.db import migrations, models
import django.db.models.deletion
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_summernote', '0002_update-help_text'),
        ('manage_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('attachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_summernote.Attachment')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('summer_field', django_summernote.fields.SummernoteTextField(default='')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('edited_date', models.DateTimeField(blank=True, null=True)),
                ('repository_url', models.URLField(blank=True, default=None, null=True)),
                ('started', models.CharField(blank=True, default=None, max_length=7, null=True)),
                ('finished', models.CharField(blank=True, default=None, max_length=7, null=True)),
                ('hashtag', models.CharField(blank=True, max_length=500, null=True)),
                ('tag1', models.CharField(blank=True, max_length=50, null=True)),
                ('tag2', models.CharField(blank=True, max_length=50, null=True)),
                ('tag3', models.CharField(blank=True, max_length=50, null=True)),
                ('tag4', models.CharField(blank=True, max_length=50, null=True)),
                ('tag5', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('django_summernote.attachment',),
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
