# Generated by Django 2.2.4 on 2019-08-16 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0002_auto_20190814_1133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repository',
        ),
    ]
