# Generated by Django 2.2.4 on 2019-08-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0004_repository'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='started',
        ),
        migrations.AddField(
            model_name='repository',
            name='period',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
