# Generated by Django 2.2.4 on 2019-08-16 04:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0005_auto_20190816_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='technique',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
