# Generated by Django 2.2.4 on 2019-08-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0006_auto_20190816_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='img1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='img/repository/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='repository',
            name='img2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='img/repository/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='repository',
            name='img3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='img/repository/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='repository',
            name='img4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='img/repository/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='repository',
            name='img5',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='img/repository/%Y/%m/%d'),
        ),
    ]
